package org.example.enumerators;

public enum UserState {
    SHARE_CONTACT,
    UPDATE_CONTACT,
    SHARE_LOCATION,
    UPDATE_LOCATION,
    REGISTERED,
    USER_MENU,
    MAIN_MANU,
    USER_VACANCIES,
    CREATING_RESUME_NAME,
    CREATING_RESUME_AGE,
    CREATING_RESUME_EDUCATION,
    CREATING_RESUME_EXPERIENCE,
    APPLYING,
    AWAITING_APPLY_TEXT,
    CREATING_VACANCY,
    MAIN_MENU,
    CREATING_VACANCY_TITLE,
    CREATING_VACANCY_COMPANY,
    CREATING_VACANCY_EXPERIENCE,
    CREATING_VACANCY_REGION,
    CREATING_VACANCY_PHONE_NUMBER,
    CREATING_VACANCY_SALARY,
    CREATING_VACANCY_PHOTO_URL,
    SEND_EMAIL,
    CREATING_VACANCY_PHONE,
    SELECTED_VACANCIES,
    SEND_CHANNEL;



}
